### ISSUE TITLE
Error on Add to Blacklist/Whitelist

### ISSUE THREAD

**Issue by tsutsu3** [tsutsu3/pi-hole-client#20]
## Expected Behavior

The process completes without displaying an error.

## Current Behavior

The screen goes dark and an error is displayed.

![crash](https://github.com/user-attachments/assets/87c2756d-734e-4c96-976b-db31620191a4)

## Steps to Reproduce

1. Click on `Logs`.
2. In the `Query Logs` page, select any query.
3. In the `Log Details` page, click `Add to blacklist/whitelist`.

## Environment

- 5a2ca0c42944dee9597b78c157ba1170fd3fa475

## Detailed

This occurs with the layout shown below (Tablet Landscape ?).

![tablet](https://github.com/user-attachments/assets/20dd3ae4-5b8a-4359-849a-fc2bf192b119)

## Log

```
The relevant error-causing widget was:
  Navigator
  Navigator:file:///C:/Users/xxx/AppData/Local/Pub/Cache/hosted/pub.dev/flutter_app_lock-4.1.1+1/lib/src/app_lock.dart:113:12

When the exception was thrown, this was the stack:
#2      NavigatorState.build (package:flutter/src/widgets/navigator.dart:5609:12)
#3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5729:27)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5617:15)
#5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#6      Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#7      StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#8      Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#10     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#11     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#12     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#13     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#14     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#21     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#22     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#24     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#25     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#27     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#29     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#30     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#31     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#32     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#34     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#36     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#37     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#38     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#39     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#41     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#42     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#43     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#46     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#47     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#48     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#49     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#50     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#51     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#53     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#55     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#56     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#57     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#58     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#59     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#60     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#61     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#62     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#63     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#64     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#65     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#67     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#72     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#74     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#75     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#76     StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#77     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#78     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#79     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#80     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#81     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#84     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#85     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#86     StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#87     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#88     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#89     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#90     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#91     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#92     ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#93     _InheritedNotifierElement.update (package:flutter/src/widgets/inherited_notifier.dart:105:11)
#94     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#95     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#96     Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#97     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#98     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#100    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#103    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#104    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#107    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#108    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#109    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#110    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#111    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#113    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#114    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#115    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#116    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#117    StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#118    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#119    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#120    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#121    StatelessElement.update (package:flutter/src/widgets/framework.dart:5693:5)
#122    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#123    SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6907:14)
#124    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#126    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#127    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#128    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#129    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#130    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#131    ProxyElement.update (package:flutter/src/widgets/framework.dart:5946:5)
#132    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#133    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#134    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#135    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#136    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#137    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#139    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#140    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#141    StatefulElement.update (package:flutter/src/widgets/framework.dart:5803:5)
#142    Element.updateChild (package:flutter/src/widgets/framework.dart:3941:15)
#143    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5642:16)
#144    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5780:11)
#145    Element.rebuild (package:flutter/src/widgets/framework.dart:5333:7)
#146    BuildScope._tryRebuild (package:flutter/src/widgets/framework.dart:2693:15)
#147    BuildScope._flushDirtyElements (package:flutter/src/widgets/framework.dart:2752:11)
#148    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3048:18)
#149    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:1162:21)
#150    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:468:5)
#151    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#152    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#153    SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1176:5)
#154    _invoke (dart:ui/hooks.dart:312:13)
#155    PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:419:5)
#156    _drawFrame (dart:ui/hooks.dart:283:31)
(elided 2 frames from class _AssertionError)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5609 pos 12: '_history.isNotEmpty': is not
true.
Another exception was thrown: 'package:flutter/src/widgets/navigator.dart': Failed assertion: line 5609 pos 12: '_history.isNotEmpty': is not
true.
...
```

**Comment by tsutsu3** [comment]
Same Domains page.
Delete domain crash
